### ISSUE TITLE
Test won't stop even after the track is finished

### ISSUE THREAD

**Issue by levilovearch** [kachayev/car-racing-attention-agent#1]
Dear kachayev,

Thanks for sharing your excellent work. To run train.py, I suggest cma should be installed as well. I'm not sure which cma version you used to develop this project but cma-3.2.2 works fine from my side.

Another issue is the simulation won't stop when running pretrained model. I tried to debug this issue and found that done is always equal to false even the track is finished. 
`
total_reward: 912.4363636363507 	done: False
total_reward: 912.3363636363507 	done: False
total_reward: 912.2363636363507 	done: False
total_reward: 915.9242424242294 	done: False
total_reward: 915.8242424242294 	done: False
total_reward: 919.5121212121081 	done: False
total_reward: 919.4121212121081 	done: False
total_reward: 919.3121212121081 	done: False
total_reward: 922.9999999999868 	done: False
total_reward: 922.8999999999868 	done: False
total_reward: 922.7999999999868 	done: False
total_reward: 922.6999999999867 	done: False
total_reward: 922.5999999999867 	done: False
total_reward: 922.4999999999867 	done: False
total_reward: 922.3999999999867 	done: False
total_reward: 922.2999999999867 	done: False
total_reward: 922.1999999999866 	done: False
total_reward: 922.0999999999866 	done: False
total_reward: 921.9999999999866 	done: False
total_reward: 921.8999999999866 	done: False
total_reward: 921.7999999999865 	done: False
total_reward: 921.6999999999865 	done: False
total_reward: 921.5999999999865 	done: False
total_reward: 921.4999999999865 	done: False
total_reward: 921.3999999999864 	done: False
total_reward: 921.2999999999864 	done: False
total_reward: 921.1999999999864 	done: False
total_reward: 921.0999999999864 	done: False
total_reward: 920.9999999999864 	done: False
total_reward: 920.8999999999863 	done: False
total_reward: 920.7999999999863 	done: False
total_reward: 920.6999999999863 	done: False
total_reward: 920.5999999999863 	done: False
total_reward: 920.4999999999862 	done: False
total_reward: 920.3999999999862 	done: False
total_reward: 920.2999999999862 	done: False
total_reward: 920.1999999999862 	done: False
total_reward: 920.0999999999862 	done: False
total_reward: 919.9999999999861 	done: False
total_reward: 919.8999999999861 	done: False
total_reward: 919.7999999999861 	done: False
total_reward: 919.6999999999861 	done: False
total_reward: 919.599999999986 	done: False
total_reward: 919.499999999986 	done: False
total_reward: 919.399999999986 	done: False
total_reward: 919.299999999986 	done: False
total_reward: 919.199999999986 	done: False
total_reward: 919.0999999999859 	done: False
total_reward: 918.9999999999859 	done: False
total_reward: 918.8999999999859 	done: False
total_reward: 918.7999999999859 	done: False
total_reward: 918.6999999999858 	done: False
total_reward: 918.5999999999858 	done: False
total_reward: 918.4999999999858 	done: False
total_reward: 918.3999999999858 	done: False
total_reward: 918.2999999999857 	done: False
total_reward: 918.1999999999857 	done: False
total_reward: 918.0999999999857 	done: False
total_reward: 917.9999999999857 	done: False
total_reward: 917.8999999999857 	done: False
total_reward: 917.7999999999856 	done: False
`

**Comment by kachayev** [comment]
Oh, interesting.

Let me check, I'm not sure I've seen anything like this before.

**Comment by kachayev** [comment]
@levilovearch I fixed the issue. Completely missed that with the new API, reaching max steps results in `timeout` rather than in `done`.

**Comment by levilovearch** [comment]
Well done sir.
